name: Publish build-info to JFrog
description: "Publishes build-info to JFrog"

inputs:
  jfrog-platform-url:
    description: ""
    required: false
    default: https://aerospike.jfrog.io
  oidc-provider:
    description: ""
    required: true
  oidc-audience:
    description: ""
    required: true
  build-path:
    description: ""
    required: true
  variables:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug publish to github
      shell: bash
      run: |
        echo "${{ inputs.jfrog-platform-url }}"
        echo "${{ inputs.build-path }}"

    - name: Set up JFrog credentials
      id: setup-jfrog-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ inputs.jfrog-platform-url }}
      with:
        version: 2.72.2
        oidc-provider-name: ${{ inputs.oidc-provider }}
        oidc-audience: ${{ inputs.oidc-audience }}

    - name: Set env variables provided with variables
      shell: bash
      run: |
        ENV_VARIABLES='${{ inputs.variables }}'
        echo "$ENV_VARIABLES" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV

    - name: Upload artifacts
      shell: bash
      run: |
        BUILD_ID=$(echo "${{ inputs.build-path }}" | sed 's/.*_\(.*\)\/.*/\1/')
        BUILD_PATH="promote_${BUILD_ID}"

        # record env variables 
        jf rt bce ${BUILD_PATH} ${{ github.run_number }}

        # record git info
        jf rt bag ${BUILD_PATH} ${{ github.run_number }}

        # publish build info
        jf rt bp ${BUILD_PATH} ${{ github.run_number }}
