name: aerospike-client-java

container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-java:openjdk-21

build:
  - name: build
    script:
      - mvn clean
      - mvn install
      - mvn -f client/pom.xml javadoc:javadoc javadoc:jar
    artifact:
      - client/target/*.jar
      - benchmarks/target/*.jar
