#!/bin/bash -e
# The default crypto library is gnu-crypto.
# This script can change crypto library to bouncy castle's bcprov-jdk18on.

# Clean up old files
function clean_up() {
  if [ -f "gnu.config" ]; then
    rm "gnu.config"
  fi

  if [ -f "bouncycastle.config" ]; then
    rm "bouncycastle.config"
  fi
}

cd $(dirname $0)

case "$1" in

gnu)
  set -x

  clean_up

  touch gnu.config
  ;;

bouncycastle)
  set -x

  clean_up

  touch bouncycastle.config
  ;;

*)
  echo "Usage: $0 gnu | bouncycastle"
  exit -1
  ;;
esac
