name: "Fast forward merge"
description: Fast forward target branch to given commit hash

inputs:
  ref-to-merge:
    description: Branch to merge into base
    required: true
  base-branch:
    description: Base branch
    required: true
  git-bot-token:
    description: Git bot token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Fetch the whole history to prevent unrelated history errors
        fetch-depth: "0"
        ref: ${{ inputs.base-branch }}
        token: ${{ inputs.git-bot-token }}

    - name: Fast forward
      shell: bash
      run: git merge --ff-only ${{ inputs.ref-to-merge }}

    - name: Add tagging message
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Promote to prod [skip ci]"
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        tagging_message: Promote to PROD
        branch: ${{ inputs.base-branch }}

    - name: Upload changes to remote head branch
      shell: bash
      run: git push
