name: "Fast forward merge"
description: Fast forward target branch to given commit hash

inputs:
  ref_to_merge:
    description: Branch to merge into base
    required: true
  base_branch:
    description: Base branch
    required: true
  git-bot-token:
    description: Git bot token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Fetch the whole history to prevent unrelated history errors
        fetch-depth: "0"
        ref: ${{ inputs.base_branch }}
        token: ${{ inputs.git-bot-token }}

    - name: Debug stuff
      shell: bash
      run: |
        git remote -vvv
    - name: Fast forward
      shell: bash
      run: git merge --ff-only ${{ inputs.ref_to_merge }}

    - name: Upload changes to remote head branch
      shell: bash
      run: git push
