// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateIndexServices.proto

package com.ltv.aerospike.api.proto;

public final class CreateIndexServices {
  private CreateIndexServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateIndexRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.CreateIndexRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string set = 2;</code>
     * @return The set.
     */
    java.lang.String getSet();
    /**
     * <code>string set = 2;</code>
     * @return The bytes for set.
     */
    com.google.protobuf.ByteString
        getSetBytes();

    /**
     * <code>string bin = 3;</code>
     * @return The bin.
     */
    java.lang.String getBin();
    /**
     * <code>string bin = 3;</code>
     * @return The bytes for bin.
     */
    com.google.protobuf.ByteString
        getBinBytes();

    /**
     * <code>string index = 4;</code>
     * @return The index.
     */
    java.lang.String getIndex();
    /**
     * <code>string index = 4;</code>
     * @return The bytes for index.
     */
    com.google.protobuf.ByteString
        getIndexBytes();

    /**
     * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
     * @return The enum numeric value on the wire for indexType.
     */
    int getIndexTypeValue();
    /**
     * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
     * @return The indexType.
     */
    com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType getIndexType();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.CreateIndexRequest}
   */
  public  static final class CreateIndexRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.CreateIndexRequest)
      CreateIndexRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateIndexRequest.newBuilder() to construct.
    private CreateIndexRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateIndexRequest() {
      namespace_ = "";
      set_ = "";
      bin_ = "";
      index_ = "";
      indexType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateIndexRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateIndexRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              set_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              bin_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              index_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              indexType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.class, com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType}
     */
    public enum IndexType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NUMERIC = 0;</code>
       */
      NUMERIC(0),
      /**
       * <code>STRING = 1;</code>
       */
      STRING(1),
      /**
       * <code>GEO2DSPHERE = 2;</code>
       */
      GEO2DSPHERE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>NUMERIC = 0;</code>
       */
      public static final int NUMERIC_VALUE = 0;
      /**
       * <code>STRING = 1;</code>
       */
      public static final int STRING_VALUE = 1;
      /**
       * <code>GEO2DSPHERE = 2;</code>
       */
      public static final int GEO2DSPHERE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IndexType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static IndexType forNumber(int value) {
        switch (value) {
          case 0: return NUMERIC;
          case 1: return STRING;
          case 2: return GEO2DSPHERE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IndexType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          IndexType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IndexType>() {
              public IndexType findValueByNumber(int number) {
                return IndexType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final IndexType[] VALUES = values();

      public static IndexType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private IndexType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType)
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SET_FIELD_NUMBER = 2;
    private volatile java.lang.Object set_;
    /**
     * <code>string set = 2;</code>
     * @return The set.
     */
    public java.lang.String getSet() {
      java.lang.Object ref = set_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        set_ = s;
        return s;
      }
    }
    /**
     * <code>string set = 2;</code>
     * @return The bytes for set.
     */
    public com.google.protobuf.ByteString
        getSetBytes() {
      java.lang.Object ref = set_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        set_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIN_FIELD_NUMBER = 3;
    private volatile java.lang.Object bin_;
    /**
     * <code>string bin = 3;</code>
     * @return The bin.
     */
    public java.lang.String getBin() {
      java.lang.Object ref = bin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bin_ = s;
        return s;
      }
    }
    /**
     * <code>string bin = 3;</code>
     * @return The bytes for bin.
     */
    public com.google.protobuf.ByteString
        getBinBytes() {
      java.lang.Object ref = bin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_FIELD_NUMBER = 4;
    private volatile java.lang.Object index_;
    /**
     * <code>string index = 4;</code>
     * @return The index.
     */
    public java.lang.String getIndex() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        index_ = s;
        return s;
      }
    }
    /**
     * <code>string index = 4;</code>
     * @return The bytes for index.
     */
    public com.google.protobuf.ByteString
        getIndexBytes() {
      java.lang.Object ref = index_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        index_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXTYPE_FIELD_NUMBER = 5;
    private int indexType_;
    /**
     * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
     * @return The enum numeric value on the wire for indexType.
     */
    public int getIndexTypeValue() {
      return indexType_;
    }
    /**
     * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
     * @return The indexType.
     */
    public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType getIndexType() {
      @SuppressWarnings("deprecation")
      com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType result = com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.valueOf(indexType_);
      return result == null ? com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getSetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, set_);
      }
      if (!getBinBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bin_);
      }
      if (!getIndexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, index_);
      }
      if (indexType_ != com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.NUMERIC.getNumber()) {
        output.writeEnum(5, indexType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getSetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, set_);
      }
      if (!getBinBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bin_);
      }
      if (!getIndexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, index_);
      }
      if (indexType_ != com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.NUMERIC.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, indexType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest other = (com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!getSet()
          .equals(other.getSet())) return false;
      if (!getBin()
          .equals(other.getBin())) return false;
      if (!getIndex()
          .equals(other.getIndex())) return false;
      if (indexType_ != other.indexType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + SET_FIELD_NUMBER;
      hash = (53 * hash) + getSet().hashCode();
      hash = (37 * hash) + BIN_FIELD_NUMBER;
      hash = (53 * hash) + getBin().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex().hashCode();
      hash = (37 * hash) + INDEXTYPE_FIELD_NUMBER;
      hash = (53 * hash) + indexType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.CreateIndexRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.CreateIndexRequest)
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.class, com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        set_ = "";

        bin_ = "";

        index_ = "";

        indexType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest build() {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest buildPartial() {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest result = new com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest(this);
        result.namespace_ = namespace_;
        result.set_ = set_;
        result.bin_ = bin_;
        result.index_ = index_;
        result.indexType_ = indexType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest) {
          return mergeFrom((com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest other) {
        if (other == com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getSet().isEmpty()) {
          set_ = other.set_;
          onChanged();
        }
        if (!other.getBin().isEmpty()) {
          bin_ = other.bin_;
          onChanged();
        }
        if (!other.getIndex().isEmpty()) {
          index_ = other.index_;
          onChanged();
        }
        if (other.indexType_ != 0) {
          setIndexTypeValue(other.getIndexTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object set_ = "";
      /**
       * <code>string set = 2;</code>
       * @return The set.
       */
      public java.lang.String getSet() {
        java.lang.Object ref = set_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          set_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string set = 2;</code>
       * @return The bytes for set.
       */
      public com.google.protobuf.ByteString
          getSetBytes() {
        java.lang.Object ref = set_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          set_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string set = 2;</code>
       * @param value The set to set.
       * @return This builder for chaining.
       */
      public Builder setSet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        set_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string set = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSet() {
        
        set_ = getDefaultInstance().getSet();
        onChanged();
        return this;
      }
      /**
       * <code>string set = 2;</code>
       * @param value The bytes for set to set.
       * @return This builder for chaining.
       */
      public Builder setSetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        set_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object bin_ = "";
      /**
       * <code>string bin = 3;</code>
       * @return The bin.
       */
      public java.lang.String getBin() {
        java.lang.Object ref = bin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bin = 3;</code>
       * @return The bytes for bin.
       */
      public com.google.protobuf.ByteString
          getBinBytes() {
        java.lang.Object ref = bin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bin = 3;</code>
       * @param value The bin to set.
       * @return This builder for chaining.
       */
      public Builder setBin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bin = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBin() {
        
        bin_ = getDefaultInstance().getBin();
        onChanged();
        return this;
      }
      /**
       * <code>string bin = 3;</code>
       * @param value The bytes for bin to set.
       * @return This builder for chaining.
       */
      public Builder setBinBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object index_ = "";
      /**
       * <code>string index = 4;</code>
       * @return The index.
       */
      public java.lang.String getIndex() {
        java.lang.Object ref = index_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          index_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string index = 4;</code>
       * @return The bytes for index.
       */
      public com.google.protobuf.ByteString
          getIndexBytes() {
        java.lang.Object ref = index_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          index_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string index = 4;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = getDefaultInstance().getIndex();
        onChanged();
        return this;
      }
      /**
       * <code>string index = 4;</code>
       * @param value The bytes for index to set.
       * @return This builder for chaining.
       */
      public Builder setIndexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        index_ = value;
        onChanged();
        return this;
      }

      private int indexType_ = 0;
      /**
       * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
       * @return The enum numeric value on the wire for indexType.
       */
      public int getIndexTypeValue() {
        return indexType_;
      }
      /**
       * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
       * @param value The enum numeric value on the wire for indexType to set.
       * @return This builder for chaining.
       */
      public Builder setIndexTypeValue(int value) {
        indexType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
       * @return The indexType.
       */
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType getIndexType() {
        @SuppressWarnings("deprecation")
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType result = com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.valueOf(indexType_);
        return result == null ? com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
       * @param value The indexType to set.
       * @return This builder for chaining.
       */
      public Builder setIndexType(com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest.IndexType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        indexType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.ltv.aerospike.api.proto.CreateIndexRequest.IndexType indexType = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndexType() {
        
        indexType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.CreateIndexRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.CreateIndexRequest)
    private static final com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest();
    }

    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateIndexRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateIndexRequest>() {
      @java.lang.Override
      public CreateIndexRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateIndexRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateIndexRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateIndexRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateIndexResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.CreateIndexResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.CreateIndexResponse}
   */
  public  static final class CreateIndexResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.CreateIndexResponse)
      CreateIndexResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateIndexResponse.newBuilder() to construct.
    private CreateIndexResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateIndexResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateIndexResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateIndexResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.class, com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse other = (com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse) obj;

      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.CreateIndexResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.CreateIndexResponse)
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.class, com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse build() {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse buildPartial() {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse result = new com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse(this);
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse) {
          return mergeFrom((com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse other) {
        if (other == com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 1;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.CreateIndexResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.CreateIndexResponse)
    private static final com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse();
    }

    public static com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateIndexResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateIndexResponse>() {
      @java.lang.Override
      public CreateIndexResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateIndexResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateIndexResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateIndexResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.CreateIndexServices.CreateIndexResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CreateIndexServices.proto\022\033com.ltv.aer" +
      "ospike.api.proto\"\325\001\n\022CreateIndexRequest\022" +
      "\021\n\tnamespace\030\001 \001(\t\022\013\n\003set\030\002 \001(\t\022\013\n\003bin\030\003" +
      " \001(\t\022\r\n\005index\030\004 \001(\t\022L\n\tindexType\030\005 \001(\01629" +
      ".com.ltv.aerospike.api.proto.CreateIndex" +
      "Request.IndexType\"5\n\tIndexType\022\013\n\007NUMERI" +
      "C\020\000\022\n\n\006STRING\020\001\022\017\n\013GEO2DSPHERE\020\002\"(\n\023Crea" +
      "teIndexResponse\022\021\n\terrorCode\030\001 \001(\0052\206\001\n\022C" +
      "reateIndexService\022p\n\013createIndex\022/.com.l" +
      "tv.aerospike.api.proto.CreateIndexReques" +
      "t\0320.com.ltv.aerospike.api.proto.CreateIn" +
      "dexResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_CreateIndexRequest_descriptor,
        new java.lang.String[] { "Namespace", "Set", "Bin", "Index", "IndexType", });
    internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_CreateIndexResponse_descriptor,
        new java.lang.String[] { "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
