// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateSetServices.proto

package com.ltv.aerospike.api.proto;

public final class CreateSetServices {
  private CreateSetServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateSetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.CreateSetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();

    /**
     * <code>string set = 2;</code>
     * @return The set.
     */
    java.lang.String getSet();
    /**
     * <code>string set = 2;</code>
     * @return The bytes for set.
     */
    com.google.protobuf.ByteString
        getSetBytes();

    /**
     * <code>string key = 3;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 3;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */
    int getStringParamsCount();
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */
    boolean containsStringParams(
        java.lang.String key);
    /**
     * Use {@link #getStringParamsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getStringParams();
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getStringParamsMap();
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    java.lang.String getStringParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    java.lang.String getStringParamsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.CreateSetRequest}
   */
  public  static final class CreateSetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.CreateSetRequest)
      CreateSetRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateSetRequest.newBuilder() to construct.
    private CreateSetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSetRequest() {
      namespace_ = "";
      set_ = "";
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateSetRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateSetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              set_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stringParams_ = com.google.protobuf.MapField.newMapField(
                    StringParamsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              stringParams__ = input.readMessage(
                  StringParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              stringParams_.getMutableMap().put(
                  stringParams__.getKey(), stringParams__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetStringParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.class, com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SET_FIELD_NUMBER = 2;
    private volatile java.lang.Object set_;
    /**
     * <code>string set = 2;</code>
     * @return The set.
     */
    public java.lang.String getSet() {
      java.lang.Object ref = set_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        set_ = s;
        return s;
      }
    }
    /**
     * <code>string set = 2;</code>
     * @return The bytes for set.
     */
    public com.google.protobuf.ByteString
        getSetBytes() {
      java.lang.Object ref = set_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        set_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 3;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 3;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRINGPARAMS_FIELD_NUMBER = 4;
    private static final class StringParamsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> stringParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetStringParams() {
      if (stringParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StringParamsDefaultEntryHolder.defaultEntry);
      }
      return stringParams_;
    }

    public int getStringParamsCount() {
      return internalGetStringParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    public boolean containsStringParams(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetStringParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStringParamsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getStringParams() {
      return getStringParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getStringParamsMap() {
      return internalGetStringParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    public java.lang.String getStringParamsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; stringParams = 4;</code>
     */

    public java.lang.String getStringParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetStringParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      if (!getSetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, set_);
      }
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStringParams(),
          StringParamsDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      if (!getSetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, set_);
      }
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetStringParams().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        stringParams__ = StringParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, stringParams__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest other = (com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!getSet()
          .equals(other.getSet())) return false;
      if (!getKey()
          .equals(other.getKey())) return false;
      if (!internalGetStringParams().equals(
          other.internalGetStringParams())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (37 * hash) + SET_FIELD_NUMBER;
      hash = (53 * hash) + getSet().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (!internalGetStringParams().getMap().isEmpty()) {
        hash = (37 * hash) + STRINGPARAMS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStringParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.CreateSetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.CreateSetRequest)
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetStringParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableStringParams();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.class, com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        set_ = "";

        key_ = "";

        internalGetMutableStringParams().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest build() {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest buildPartial() {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest result = new com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest(this);
        int from_bitField0_ = bitField0_;
        result.namespace_ = namespace_;
        result.set_ = set_;
        result.key_ = key_;
        result.stringParams_ = internalGetStringParams();
        result.stringParams_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest) {
          return mergeFrom((com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest other) {
        if (other == com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        if (!other.getSet().isEmpty()) {
          set_ = other.set_;
          onChanged();
        }
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        internalGetMutableStringParams().mergeFrom(
            other.internalGetStringParams());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object set_ = "";
      /**
       * <code>string set = 2;</code>
       * @return The set.
       */
      public java.lang.String getSet() {
        java.lang.Object ref = set_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          set_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string set = 2;</code>
       * @return The bytes for set.
       */
      public com.google.protobuf.ByteString
          getSetBytes() {
        java.lang.Object ref = set_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          set_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string set = 2;</code>
       * @param value The set to set.
       * @return This builder for chaining.
       */
      public Builder setSet(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        set_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string set = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSet() {
        
        set_ = getDefaultInstance().getSet();
        onChanged();
        return this;
      }
      /**
       * <code>string set = 2;</code>
       * @param value The bytes for set to set.
       * @return This builder for chaining.
       */
      public Builder setSetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        set_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 3;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 3;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 3;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> stringParams_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetStringParams() {
        if (stringParams_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StringParamsDefaultEntryHolder.defaultEntry);
        }
        return stringParams_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableStringParams() {
        onChanged();;
        if (stringParams_ == null) {
          stringParams_ = com.google.protobuf.MapField.newMapField(
              StringParamsDefaultEntryHolder.defaultEntry);
        }
        if (!stringParams_.isMutable()) {
          stringParams_ = stringParams_.copy();
        }
        return stringParams_;
      }

      public int getStringParamsCount() {
        return internalGetStringParams().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public boolean containsStringParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStringParams().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStringParamsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getStringParams() {
        return getStringParamsMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getStringParamsMap() {
        return internalGetStringParams().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public java.lang.String getStringParamsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStringParams().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public java.lang.String getStringParamsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetStringParams().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStringParams() {
        internalGetMutableStringParams().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public Builder removeStringParams(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStringParams().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableStringParams() {
        return internalGetMutableStringParams().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */
      public Builder putStringParams(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStringParams().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; stringParams = 4;</code>
       */

      public Builder putAllStringParams(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableStringParams().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.CreateSetRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.CreateSetRequest)
    private static final com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest();
    }

    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSetRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateSetRequest>() {
      @java.lang.Override
      public CreateSetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateSetRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSetRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateSetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.CreateSetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 setId = 1;</code>
     * @return The setId.
     */
    int getSetId();

    /**
     * <code>int32 errorCode = 2;</code>
     * @return The errorCode.
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.CreateSetResponse}
   */
  public  static final class CreateSetResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.CreateSetResponse)
      CreateSetResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateSetResponse.newBuilder() to construct.
    private CreateSetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSetResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateSetResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateSetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              setId_ = input.readInt32();
              break;
            }
            case 16: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.class, com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.Builder.class);
    }

    public static final int SETID_FIELD_NUMBER = 1;
    private int setId_;
    /**
     * <code>int32 setId = 1;</code>
     * @return The setId.
     */
    public int getSetId() {
      return setId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 2;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (setId_ != 0) {
        output.writeInt32(1, setId_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(2, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (setId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, setId_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse other = (com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse) obj;

      if (getSetId()
          != other.getSetId()) return false;
      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SETID_FIELD_NUMBER;
      hash = (53 * hash) + getSetId();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.CreateSetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.CreateSetResponse)
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.class, com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        setId_ = 0;

        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.CreateSetServices.internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse build() {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse buildPartial() {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse result = new com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse(this);
        result.setId_ = setId_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse) {
          return mergeFrom((com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse other) {
        if (other == com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse.getDefaultInstance()) return this;
        if (other.getSetId() != 0) {
          setSetId(other.getSetId());
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int setId_ ;
      /**
       * <code>int32 setId = 1;</code>
       * @return The setId.
       */
      public int getSetId() {
        return setId_;
      }
      /**
       * <code>int32 setId = 1;</code>
       * @param value The setId to set.
       * @return This builder for chaining.
       */
      public Builder setSetId(int value) {
        
        setId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 setId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSetId() {
        
        setId_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 2;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 2;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.CreateSetResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.CreateSetResponse)
    private static final com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse();
    }

    public static com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSetResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateSetResponse>() {
      @java.lang.Override
      public CreateSetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateSetResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateSetResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSetResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.CreateSetServices.CreateSetResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CreateSetServices.proto\022\033com.ltv.aeros" +
      "pike.api.proto\"\313\001\n\020CreateSetRequest\022\021\n\tn" +
      "amespace\030\001 \001(\t\022\013\n\003set\030\002 \001(\t\022\013\n\003key\030\003 \001(\t" +
      "\022U\n\014stringParams\030\004 \003(\0132?.com.ltv.aerospi" +
      "ke.api.proto.CreateSetRequest.StringPara" +
      "msEntry\0323\n\021StringParamsEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"5\n\021CreateSetRespons" +
      "e\022\r\n\005setId\030\001 \001(\005\022\021\n\terrorCode\030\002 \001(\0052~\n\020C" +
      "reateSetService\022j\n\tcreateSet\022-.com.ltv.a" +
      "erospike.api.proto.CreateSetRequest\032..co" +
      "m.ltv.aerospike.api.proto.CreateSetRespo" +
      "nseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor,
        new java.lang.String[] { "Namespace", "Set", "Key", "StringParams", });
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_descriptor =
      internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_CreateSetRequest_StringParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_CreateSetResponse_descriptor,
        new java.lang.String[] { "SetId", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
