// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RenameNamespaceServices.proto

package com.ltv.aerospike.api.proto;

public final class RenameNamespaceServices {
  private RenameNamespaceServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RenameNamespaceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.RenameNamespaceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string oldName = 1;</code>
     * @return The oldName.
     */
    java.lang.String getOldName();
    /**
     * <code>string oldName = 1;</code>
     * @return The bytes for oldName.
     */
    com.google.protobuf.ByteString
        getOldNameBytes();

    /**
     * <code>string newName = 2;</code>
     * @return The newName.
     */
    java.lang.String getNewName();
    /**
     * <code>string newName = 2;</code>
     * @return The bytes for newName.
     */
    com.google.protobuf.ByteString
        getNewNameBytes();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.RenameNamespaceRequest}
   */
  public  static final class RenameNamespaceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.RenameNamespaceRequest)
      RenameNamespaceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RenameNamespaceRequest.newBuilder() to construct.
    private RenameNamespaceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RenameNamespaceRequest() {
      oldName_ = "";
      newName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RenameNamespaceRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RenameNamespaceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              oldName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              newName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.class, com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.Builder.class);
    }

    public static final int OLDNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object oldName_;
    /**
     * <code>string oldName = 1;</code>
     * @return The oldName.
     */
    public java.lang.String getOldName() {
      java.lang.Object ref = oldName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oldName_ = s;
        return s;
      }
    }
    /**
     * <code>string oldName = 1;</code>
     * @return The bytes for oldName.
     */
    public com.google.protobuf.ByteString
        getOldNameBytes() {
      java.lang.Object ref = oldName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEWNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object newName_;
    /**
     * <code>string newName = 2;</code>
     * @return The newName.
     */
    public java.lang.String getNewName() {
      java.lang.Object ref = newName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newName_ = s;
        return s;
      }
    }
    /**
     * <code>string newName = 2;</code>
     * @return The bytes for newName.
     */
    public com.google.protobuf.ByteString
        getNewNameBytes() {
      java.lang.Object ref = newName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOldNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oldName_);
      }
      if (!getNewNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOldNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oldName_);
      }
      if (!getNewNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest other = (com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest) obj;

      if (!getOldName()
          .equals(other.getOldName())) return false;
      if (!getNewName()
          .equals(other.getNewName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OLDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOldName().hashCode();
      hash = (37 * hash) + NEWNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNewName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.RenameNamespaceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.RenameNamespaceRequest)
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.class, com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        oldName_ = "";

        newName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest build() {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest buildPartial() {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest result = new com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest(this);
        result.oldName_ = oldName_;
        result.newName_ = newName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest) {
          return mergeFrom((com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest other) {
        if (other == com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest.getDefaultInstance()) return this;
        if (!other.getOldName().isEmpty()) {
          oldName_ = other.oldName_;
          onChanged();
        }
        if (!other.getNewName().isEmpty()) {
          newName_ = other.newName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object oldName_ = "";
      /**
       * <code>string oldName = 1;</code>
       * @return The oldName.
       */
      public java.lang.String getOldName() {
        java.lang.Object ref = oldName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oldName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string oldName = 1;</code>
       * @return The bytes for oldName.
       */
      public com.google.protobuf.ByteString
          getOldNameBytes() {
        java.lang.Object ref = oldName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string oldName = 1;</code>
       * @param value The oldName to set.
       * @return This builder for chaining.
       */
      public Builder setOldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oldName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string oldName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldName() {
        
        oldName_ = getDefaultInstance().getOldName();
        onChanged();
        return this;
      }
      /**
       * <code>string oldName = 1;</code>
       * @param value The bytes for oldName to set.
       * @return This builder for chaining.
       */
      public Builder setOldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oldName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object newName_ = "";
      /**
       * <code>string newName = 2;</code>
       * @return The newName.
       */
      public java.lang.String getNewName() {
        java.lang.Object ref = newName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          newName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string newName = 2;</code>
       * @return The bytes for newName.
       */
      public com.google.protobuf.ByteString
          getNewNameBytes() {
        java.lang.Object ref = newName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string newName = 2;</code>
       * @param value The newName to set.
       * @return This builder for chaining.
       */
      public Builder setNewName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        newName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string newName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewName() {
        
        newName_ = getDefaultInstance().getNewName();
        onChanged();
        return this;
      }
      /**
       * <code>string newName = 2;</code>
       * @param value The bytes for newName to set.
       * @return This builder for chaining.
       */
      public Builder setNewNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        newName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.RenameNamespaceRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.RenameNamespaceRequest)
    private static final com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest();
    }

    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RenameNamespaceRequest>
        PARSER = new com.google.protobuf.AbstractParser<RenameNamespaceRequest>() {
      @java.lang.Override
      public RenameNamespaceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RenameNamespaceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RenameNamespaceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RenameNamespaceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RenameNamespaceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.RenameNamespaceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.RenameNamespaceResponse}
   */
  public  static final class RenameNamespaceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.RenameNamespaceResponse)
      RenameNamespaceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RenameNamespaceResponse.newBuilder() to construct.
    private RenameNamespaceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RenameNamespaceResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RenameNamespaceResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RenameNamespaceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.class, com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse other = (com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse) obj;

      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.RenameNamespaceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.RenameNamespaceResponse)
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.class, com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse build() {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse buildPartial() {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse result = new com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse(this);
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse) {
          return mergeFrom((com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse other) {
        if (other == com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 1;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.RenameNamespaceResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.RenameNamespaceResponse)
    private static final com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse();
    }

    public static com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RenameNamespaceResponse>
        PARSER = new com.google.protobuf.AbstractParser<RenameNamespaceResponse>() {
      @java.lang.Override
      public RenameNamespaceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RenameNamespaceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RenameNamespaceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RenameNamespaceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.RenameNamespaceServices.RenameNamespaceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035RenameNamespaceServices.proto\022\033com.ltv" +
      ".aerospike.api.proto\":\n\026RenameNamespaceR" +
      "equest\022\017\n\007oldName\030\001 \001(\t\022\017\n\007newName\030\002 \001(\t" +
      "\",\n\027RenameNamespaceResponse\022\021\n\terrorCode" +
      "\030\001 \001(\0052\226\001\n\026RenameNamespaceService\022|\n\017ren" +
      "ameNamespace\0223.com.ltv.aerospike.api.pro" +
      "to.RenameNamespaceRequest\0324.com.ltv.aero" +
      "spike.api.proto.RenameNamespaceResponseb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_RenameNamespaceRequest_descriptor,
        new java.lang.String[] { "OldName", "NewName", });
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_RenameNamespaceResponse_descriptor,
        new java.lang.String[] { "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
