// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowIndexServices.proto

package com.ltv.aerospike.api.proto;

public final class ShowIndexServices {
  private ShowIndexServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShowIndexRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.ShowIndexRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.ShowIndexRequest}
   */
  public  static final class ShowIndexRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.ShowIndexRequest)
      ShowIndexRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShowIndexRequest.newBuilder() to construct.
    private ShowIndexRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShowIndexRequest() {
      namespace_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShowIndexRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShowIndexRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.class, com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest other = (com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.ShowIndexRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.ShowIndexRequest)
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.class, com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest build() {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest buildPartial() {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest result = new com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest(this);
        result.namespace_ = namespace_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest) {
          return mergeFrom((com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest other) {
        if (other == com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.ShowIndexRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.ShowIndexRequest)
    private static final com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest();
    }

    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShowIndexRequest>
        PARSER = new com.google.protobuf.AbstractParser<ShowIndexRequest>() {
      @java.lang.Override
      public ShowIndexRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowIndexRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShowIndexRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShowIndexRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShowIndexResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.ShowIndexResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    int getErrorCode();

    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */
    int getIndexsCount();
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */
    boolean containsIndexs(
        java.lang.String key);
    /**
     * Use {@link #getIndexsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getIndexs();
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getIndexsMap();
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    java.lang.String getIndexsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    java.lang.String getIndexsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.ShowIndexResponse}
   */
  public  static final class ShowIndexResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.ShowIndexResponse)
      ShowIndexResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShowIndexResponse.newBuilder() to construct.
    private ShowIndexResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShowIndexResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShowIndexResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShowIndexResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                indexs_ = com.google.protobuf.MapField.newMapField(
                    IndexsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              indexs__ = input.readMessage(
                  IndexsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              indexs_.getMutableMap().put(
                  indexs__.getKey(), indexs__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetIndexs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.class, com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int INDEXS_FIELD_NUMBER = 2;
    private static final class IndexsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> indexs_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetIndexs() {
      if (indexs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            IndexsDefaultEntryHolder.defaultEntry);
      }
      return indexs_;
    }

    public int getIndexsCount() {
      return internalGetIndexs().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    public boolean containsIndexs(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetIndexs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getIndexsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getIndexs() {
      return getIndexsMap();
    }
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getIndexsMap() {
      return internalGetIndexs().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    public java.lang.String getIndexsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetIndexs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; indexs = 2;</code>
     */

    public java.lang.String getIndexsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetIndexs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetIndexs(),
          IndexsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetIndexs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        indexs__ = IndexsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, indexs__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse other = (com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse) obj;

      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!internalGetIndexs().equals(
          other.internalGetIndexs())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      if (!internalGetIndexs().getMap().isEmpty()) {
        hash = (37 * hash) + INDEXS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetIndexs().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.ShowIndexResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.ShowIndexResponse)
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetIndexs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableIndexs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.class, com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        internalGetMutableIndexs().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse build() {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse buildPartial() {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse result = new com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse(this);
        int from_bitField0_ = bitField0_;
        result.errorCode_ = errorCode_;
        result.indexs_ = internalGetIndexs();
        result.indexs_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse) {
          return mergeFrom((com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse other) {
        if (other == com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        internalGetMutableIndexs().mergeFrom(
            other.internalGetIndexs());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 1;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> indexs_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetIndexs() {
        if (indexs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              IndexsDefaultEntryHolder.defaultEntry);
        }
        return indexs_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableIndexs() {
        onChanged();;
        if (indexs_ == null) {
          indexs_ = com.google.protobuf.MapField.newMapField(
              IndexsDefaultEntryHolder.defaultEntry);
        }
        if (!indexs_.isMutable()) {
          indexs_ = indexs_.copy();
        }
        return indexs_;
      }

      public int getIndexsCount() {
        return internalGetIndexs().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public boolean containsIndexs(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetIndexs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getIndexsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getIndexs() {
        return getIndexsMap();
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getIndexsMap() {
        return internalGetIndexs().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public java.lang.String getIndexsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetIndexs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public java.lang.String getIndexsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetIndexs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearIndexs() {
        internalGetMutableIndexs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public Builder removeIndexs(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableIndexs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableIndexs() {
        return internalGetMutableIndexs().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */
      public Builder putIndexs(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableIndexs().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; indexs = 2;</code>
       */

      public Builder putAllIndexs(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableIndexs().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.ShowIndexResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.ShowIndexResponse)
    private static final com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse();
    }

    public static com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShowIndexResponse>
        PARSER = new com.google.protobuf.AbstractParser<ShowIndexResponse>() {
      @java.lang.Override
      public ShowIndexResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowIndexResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShowIndexResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShowIndexResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.ShowIndexServices.ShowIndexResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ShowIndexServices.proto\022\033com.ltv.aeros" +
      "pike.api.proto\"%\n\020ShowIndexRequest\022\021\n\tna" +
      "mespace\030\001 \001(\t\"\241\001\n\021ShowIndexResponse\022\021\n\te" +
      "rrorCode\030\001 \001(\005\022J\n\006indexs\030\002 \003(\0132:.com.ltv" +
      ".aerospike.api.proto.ShowIndexResponse.I" +
      "ndexsEntry\032-\n\013IndexsEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\0012~\n\020ShowIndexService\022j\n" +
      "\tshowIndex\022-.com.ltv.aerospike.api.proto" +
      ".ShowIndexRequest\032..com.ltv.aerospike.ap" +
      "i.proto.ShowIndexResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowIndexRequest_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "Indexs", });
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_descriptor =
      internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowIndexResponse_IndexsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
