// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowSetServices.proto

package com.ltv.aerospike.api.proto;

public final class ShowSetServices {
  private ShowSetServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ShowSetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.ShowSetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    java.lang.String getNamespace();
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    com.google.protobuf.ByteString
        getNamespaceBytes();
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.ShowSetRequest}
   */
  public  static final class ShowSetRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.ShowSetRequest)
      ShowSetRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShowSetRequest.newBuilder() to construct.
    private ShowSetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShowSetRequest() {
      namespace_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShowSetRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShowSetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              namespace_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.class, com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.Builder.class);
    }

    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private volatile java.lang.Object namespace_;
    /**
     * <code>string namespace = 1;</code>
     * @return The namespace.
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      }
    }
    /**
     * <code>string namespace = 1;</code>
     * @return The bytes for namespace.
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNamespaceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespace_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNamespaceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespace_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest other = (com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest) obj;

      if (!getNamespace()
          .equals(other.getNamespace())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getNamespace().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.ShowSetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.ShowSetRequest)
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.class, com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        namespace_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest build() {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest buildPartial() {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest result = new com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest(this);
        result.namespace_ = namespace_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest) {
          return mergeFrom((com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest other) {
        if (other == com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest.getDefaultInstance()) return this;
        if (!other.getNamespace().isEmpty()) {
          namespace_ = other.namespace_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object namespace_ = "";
      /**
       * <code>string namespace = 1;</code>
       * @return The namespace.
       */
      public java.lang.String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @return The bytes for namespace.
       */
      public com.google.protobuf.ByteString
          getNamespaceBytes() {
        java.lang.Object ref = namespace_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namespace_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespace(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        namespace_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNamespace() {
        
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      /**
       * <code>string namespace = 1;</code>
       * @param value The bytes for namespace to set.
       * @return This builder for chaining.
       */
      public Builder setNamespaceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        namespace_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.ShowSetRequest)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.ShowSetRequest)
    private static final com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest();
    }

    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShowSetRequest>
        PARSER = new com.google.protobuf.AbstractParser<ShowSetRequest>() {
      @java.lang.Override
      public ShowSetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowSetRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShowSetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShowSetRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ShowSetResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ltv.aerospike.api.proto.ShowSetResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    int getErrorCode();

    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */
    int getSetsCount();
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */
    boolean containsSets(
        java.lang.String key);
    /**
     * Use {@link #getSetsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getSets();
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getSetsMap();
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    java.lang.String getSetsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    java.lang.String getSetsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.ltv.aerospike.api.proto.ShowSetResponse}
   */
  public  static final class ShowSetResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ltv.aerospike.api.proto.ShowSetResponse)
      ShowSetResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ShowSetResponse.newBuilder() to construct.
    private ShowSetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ShowSetResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ShowSetResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ShowSetResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              errorCode_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                sets_ = com.google.protobuf.MapField.newMapField(
                    SetsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              sets__ = input.readMessage(
                  SetsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              sets_.getMutableMap().put(
                  sets__.getKey(), sets__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetSets();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.class, com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int SETS_FIELD_NUMBER = 2;
    private static final class SetsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> sets_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSets() {
      if (sets_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SetsDefaultEntryHolder.defaultEntry);
      }
      return sets_;
    }

    public int getSetsCount() {
      return internalGetSets().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    public boolean containsSets(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSets().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSetsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSets() {
      return getSetsMap();
    }
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getSetsMap() {
      return internalGetSets().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    public java.lang.String getSetsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSets().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; sets = 2;</code>
     */

    public java.lang.String getSetsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSets().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != 0) {
        output.writeInt32(1, errorCode_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetSets(),
          SetsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSets().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        sets__ = SetsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, sets__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse)) {
        return super.equals(obj);
      }
      com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse other = (com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse) obj;

      if (getErrorCode()
          != other.getErrorCode()) return false;
      if (!internalGetSets().equals(
          other.internalGetSets())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      if (!internalGetSets().getMap().isEmpty()) {
        hash = (37 * hash) + SETS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSets().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ltv.aerospike.api.proto.ShowSetResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ltv.aerospike.api.proto.ShowSetResponse)
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetSets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableSets();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.class, com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.Builder.class);
      }

      // Construct using com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        errorCode_ = 0;

        internalGetMutableSets().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ltv.aerospike.api.proto.ShowSetServices.internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse getDefaultInstanceForType() {
        return com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse build() {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse buildPartial() {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse result = new com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse(this);
        int from_bitField0_ = bitField0_;
        result.errorCode_ = errorCode_;
        result.sets_ = internalGetSets();
        result.sets_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse) {
          return mergeFrom((com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse other) {
        if (other == com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse.getDefaultInstance()) return this;
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        internalGetMutableSets().mergeFrom(
            other.internalGetSets());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorCode_ ;
      /**
       * <code>int32 errorCode = 1;</code>
       * @return The errorCode.
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> sets_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetSets() {
        if (sets_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SetsDefaultEntryHolder.defaultEntry);
        }
        return sets_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableSets() {
        onChanged();;
        if (sets_ == null) {
          sets_ = com.google.protobuf.MapField.newMapField(
              SetsDefaultEntryHolder.defaultEntry);
        }
        if (!sets_.isMutable()) {
          sets_ = sets_.copy();
        }
        return sets_;
      }

      public int getSetsCount() {
        return internalGetSets().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public boolean containsSets(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetSets().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSetsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSets() {
        return getSetsMap();
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getSetsMap() {
        return internalGetSets().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public java.lang.String getSetsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSets().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public java.lang.String getSetsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSets().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearSets() {
        internalGetMutableSets().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public Builder removeSets(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableSets().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableSets() {
        return internalGetMutableSets().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */
      public Builder putSets(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableSets().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; sets = 2;</code>
       */

      public Builder putAllSets(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableSets().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ltv.aerospike.api.proto.ShowSetResponse)
    }

    // @@protoc_insertion_point(class_scope:com.ltv.aerospike.api.proto.ShowSetResponse)
    private static final com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse();
    }

    public static com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ShowSetResponse>
        PARSER = new com.google.protobuf.AbstractParser<ShowSetResponse>() {
      @java.lang.Override
      public ShowSetResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShowSetResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ShowSetResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ShowSetResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ltv.aerospike.api.proto.ShowSetServices.ShowSetResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ShowSetServices.proto\022\033com.ltv.aerospi" +
      "ke.api.proto\"#\n\016ShowSetRequest\022\021\n\tnamesp" +
      "ace\030\001 \001(\t\"\227\001\n\017ShowSetResponse\022\021\n\terrorCo" +
      "de\030\001 \001(\005\022D\n\004sets\030\002 \003(\01326.com.ltv.aerospi" +
      "ke.api.proto.ShowSetResponse.SetsEntry\032+" +
      "\n\tSetsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\0012v\n\016ShowSetService\022d\n\007showSet\022+.com.l" +
      "tv.aerospike.api.proto.ShowSetRequest\032,." +
      "com.ltv.aerospike.api.proto.ShowSetRespo" +
      "nseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowSetRequest_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor,
        new java.lang.String[] { "ErrorCode", "Sets", });
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_descriptor =
      internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ltv_aerospike_api_proto_ShowSetResponse_SetsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
