#!/bin/bash
# Build, package and release the current client branch.
# Only the build master should be using this script.

cd `dirname $0`
source run_command

runCommand ./build
runCommand ./package
runCommand ./release
exit 0
