#!/bin/sh

if [ $# -lt 2 ]
then
    echo "Usage: $0 <version> <filename>"
    exit
fi

version=$1
fn=$2

awk 'BEGIN{OFS=""}
{
    if (index($0,"<artifactId>aerospike") > 0)
    {
        found = 1
    }
    if (found == 1)
    {
        idx = index($0,"<version>"); 
        if (idx > 0) 
        {
            print substr($0, 0, idx+8),"'$version'</version>";
            found = 0
        } 
        else
        {
            print $0
        }
    }
    else
    {
        print $0
    }
}' $fn > $fn.tmp

mv $fn.tmp $fn
