#!/bin/sh
fn=$1

origin=`pwd`
cd `dirname $0`
source run_command
cd $origin

version=`./version`

awk 'BEGIN{OFS=""}
{
    if (index($0,"<artifactId>aerospike") > 0)
    {
        found = 1
    }
    if (found == 1)
    {
        idx = index($0,"<version>"); 
        if (idx > 0) 
        {
            print substr($0, 0, idx+8),"'$version'</version>";
            found = 0
        } 
        else
        {
            print $0
        }
    }
    else
    {
        print $0
    }
}' $fn
