#!/bin/bash
# Release client package to shared directory.

cd `dirname $0`
source run_command

version=`./version`
trgdir=/mnt/release/client/$version

runCommand mkdir -p $trgdir
runCommand cp ../package/aerospike-client*$version*.tgz $trgdir
exit 0
