#!/bin/sh

if [ $# -lt 1 ]
then
  echo "Usage: $0 stage|prod"
  exit
fi

target=$1
srcpath=../client/doc
trgpath=/var/www/website/web/java_api

if [ "$target" = "stage" ]
then
  host="builds@staging.aerospike.com"
elif [ "$target" = "prod" ]
then
  host="builds@www.aerospike.com"
else
  echo Invalid website target: $target
  echo "Usage: $0 java|csharp stage|prod"
  exit  
fi

port=6472

echo ssh -p $port $host "rm -rf $trgpath/*"
ssh -p $port $host "rm -rf $trgpath/*"

echo scp -P $port $srcpath/* $host:$trgpath
scp -P $port -r $srcpath/* $host:$trgpath

