#!/bin/bash
# Release client package to shared directory.

cd `dirname $0`
source run_command

version=`./version`
trgdir=/mnt/release/client/java/$version

runCommand mkdir -p $trgdir
runCommand cp ../package/aerospike-client-* $trgdir
exit 0
