#!/bin/bash

function runCommand {
  echo $*
  $*
  
  if [ $? -ne 0 ]
  then
    echo Command failed. Exiting!
    exit 1
  fi
}

function getRevision {
	rev=`git describe`
	subbuild=`echo $rev | awk -F'-' '{print $2}'`

	if [ "$subbuild" != "" ]
	then
	  rev=`echo $rev | awk -F'-' '{printf("%s-%s\n",$1,$2)}'`
	fi
	echo $rev
}

function isTag {
  tmp=`echo ${1:0:1} | tr '[0-9]' '%'`
  
  if [ "$tmp" = "%" ]
  then
    echo true
  else
    echo false
  fi
} 
