#!/bin/bash

function runCommand {
  echo $*
  $*
  
  if [ $? -ne 0 ]
  then
    echo Command failed. Exiting!
    exit 1
  fi
}

function isTag {
  tmp=`echo ${1:0:1} | tr '[0-9]' '%'`
  
  if [ "$tmp" = "%" ]
  then
    echo true
  else
    echo false
  fi
} 
