name: Build and est
description: "Build and test code base"

inputs:
  crypto-type:
    description: ""
    required: false
    default: gnu
  use-server-rc:
    required: false
    default: "false"
    description: "Test against server release candidate?"
  server-tag:
    required: false
    default: "latest"
    description: "Server docker image tag"
  jfrog_docker_username:
    required: true
    description: ""
  jfrog_docker_token:
    required: true
    description: ""
  run-tests:
    required: true
    default: "false"
    description: Spin up aerospike enterprise server and run tests

runs:
  using: "composite"
  steps:
    - name: Stage crypto
      shell: bash
      run: |
        ./set_cypto ${{ inputs.crypto-type }}

    - name: Build
      shell: bash
      run: mvn clean install -P ${{ inputs.crypto-type }}

    - name: Run EE server
      if: ${{ inputs.run-tests == 'true' }}
      uses: ./.github/actions/run-ee-server
      with:
        use-server-rc: ${{ inputs.use-server-rc }}
        server-tag: ${{ inputs.server-tag }}
        docker-hub-username: ${{ inputs.jfrog_docker_username }}
        docker-hub-password: ${{ inputs.jfrog_docker_token }}

    - name: Test
      shell: bash
      if: ${{ inputs.run-tests == true }}
      working-directory: test
      run: mvn test -DskipTests=false
