name: Publish artifacts to Sonatype
description: "Publishes artifacts to Sonatype"

inputs:
  jfrog-platform-url:
    description: ""
    required: false
    default: https://aerospike.jfrog.io
  oidc-provider:
    description: ""
    required: true
  oidc-audience:
    description: ""
    required: true
  staging-folder:
    description: ""
    required: false
    default: staging
  target-repository:
    description: ""
    required: false
    default: clients-maven-stage-local
  build-name-number:
    description: ""
    required: true
  artifact-version:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JFrog credentials
      id: setup-jfrog-cli
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ inputs.jfrog-platform-url }}
      with:
        version: 2.72.2
        oidc-provider-name: ${{ inputs.oidc-provider }}
        oidc-audience: ${{ inputs.oidc-audience }}

    - name: Get info
      shell: bash
      id: get-build-info
      run: |
        INPUT=${{ inputs.build-name-number }}

        BUILD_NAME="${INPUT%/*}" # Getting the build name
        BUILD_NUMBER="${INPUT#*/}" # Getting build number

        BUILD_INFO=$(jf rt curl "/api/build/${BUILD_NAME}/${BUILD_NUMBER}" | jq -c ".")
        echo build-info="${BUILD_INFO}" >> $GITHUB_OUTPUT

    - name: Get build name
      shell: bash
      id: get-build-name
      run: |
        echo build-name=$(echo '${{ steps.get-build-info.outputs.build-info }}' | jq -r '.buildInfo.modules[].id | sub("/[0-9]+$"; "")') >> $GITHUB_OUTPUT

    - name: Create staging folder
      shell: bash
      run: |
        mkdir -p ${{ inputs.staging-folder }}

    - name: Download artifacts from JFrog
      shell: bash
      working-directory: ${{ inputs.staging-folder }}
      run: |
        jf rt dl "${{ inputs.target-repository }}/com/aerospike/${{ steps.get-build-name.outputs.build-name }}/${{ inputs.artifact-version }}/*" .

    - name: Debug list downloaded content
      shell: bash
      working-directory: ${{ inputs.staging-folder }}
      run: |
        ls -laR
