name: Aerospike Java Client Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout client
      uses: actions/checkout@v2
    - name: Setup Aerospike Database
      uses: reugn/github-action-aerospike@v1
    - run: mvn install
    - run: cd test
    - run: mvn test -DskipTests=false
