name: Build artifacts

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: string
        required: true
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"
      run-tests:
        type: boolean
        required: false
        default: false
        description: Spin up aerospike enterprise server and run tests
      crypto-type:
        type: string
        required: true
    secrets:
      GPG_SECRET_KEY:
        required: true
      GPG_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASS }}

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          crypto-type: ${{ inputs.crypto-type }}
          server-tag: ${{ inputs.server-tag }}
          use-server-rc: ${{ inputs.use-server-rc }}

      - name: Publish to JFrog
        if: ${{ !cancelled() && inputs.upload-artifacts == true }}
        uses: ./.github/actions/publish-to-jfrog
        with:
          crypto-type: ${{ inputs.crypto-type }}
