run-name: Build artifact for ${{ inputs.crypto-type }} ${{ inputs.java-version }}

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: string
        required: true
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"
      run-tests:
        type: boolean
        required: false
        default: false
        description: Spin up aerospike enterprise server and run tests
      crypto-type:
        type: string
        required: true
    secrets:
      JFROG_OIDC_PROVIDER:
        required: true
      JFROG_OIDC_AUDIENCE:
        required: true

jobs:
  build:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Build and test
        uses: ./.github/actions/build-and-test
        with:
          crypto-type: ${{ inputs.crypto-type }}
          server-tag: ${{ inputs.server-tag }}
          use-server-rc: ${{ inputs.use-server-rc }}
          oidc-provider: ${{ secrets.JFROG_OIDC_PROVIDER }}
          oidc-audience: ${{ secrets.JFROG_OIDC_AUDIENCE }}
