name: Build artifacts

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: string
        required: true
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"
      run-tests:
        type: boolean
        required: false
        default: false
        description: Spin up aerospike enterprise server and run tests
      crypto-type:
        type: string
        required: true

    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_DOCKER_TOKEN:
        required: true
      GPG_SECRET_KEY:
        required: true
      GPG_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASS }}

      - name: Build
        run: mvn install -Dcrypto.type=${{ inputs.client-type == 'bouncycastle' && '-bc' || '' }}

      - name: Run EE server
        if: ${{ inputs.run-tests == true }}
        uses: ./.github/actions/run-ee-server
        with:
          use-server-rc: ${{ inputs.use-server-rc }}
          server-tag: ${{ inputs.server-tag }}
          docker-hub-username: ${{ secrets.JFROG_USERNAME }}
          docker-hub-password: ${{ secrets.JFROG_DOCKER_TOKEN }}

      - name: Test
        if: ${{ inputs.run-tests == true }}
        working-directory: test
        run: mvn test -DskipTests=false

      - name: Generate docs jar
        if: ${{ !cancelled() && inputs.upload-artifacts == true }}
        working-directory: client
        run: |
          mvn javadoc:jar

      - name: Generate sources jar
        if: ${{ !cancelled() && inputs.upload-artifacts == true }}
        working-directory: client
        run: |
          mvn source:jar

      - name: Upload to JFrog
        if: ${{ !cancelled() && inputs.upload-artifacts == true }}
        uses: ./.github/actions/upload-to-jfrog
        with:
          version: ${{ steps.get-new-version.outputs.new_version }}
          jdk-version: "jdk${{ inputs.java-version }}"
