name: Build artifacts

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      bump-version:
        type: boolean
        required: false
        default: false
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"
    secrets:
      DOCKER_HUB_BOT_USERNAME:
        required: true
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_IDENTIFIER: "${{ inputs.branch }}-${{ inputs.java-version }}"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Increment version
        if: ${{ inputs.bump-version == true }}
        run: |
          mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.\${parsedVersion.incrementalVersion} \
          versions:commit

      - name: Echo new version to CI
        if: ${{ inputs.bump-version == true }}
        id: get-new-version
        run: echo new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Commit new version
        if: ${{ inputs.bump-version == true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-bump version to ${{ inputs.new_version }} [skip ci]"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          tagging_message: ${{ inputs.new_version }}
          branch: ${{ inputs.is_workflow_call && github.ref }}

      - name: Run EE server
        uses: ./.github/actions/run-ee-server
        with:
          use-server-rc: ${{ inputs.use-server-rc }}
          server-tag: ${{ inputs.server-tag }}
          docker-hub-username: ${{ secrets.DOCKER_HUB_BOT_USERNAME }}
          docker-hub-password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build
        run: mvn install

      - name: Test
        working-directory: test
        run: mvn test -DskipTests=false

      - name: Upload jars to GitHub
        if: ${{ !cancelled() && inputs.upload-artifacts == true }}
        uses: actions/upload-artifact@v4
        with:
          path: ./*/target/*.jar
          name: ${{ env.BUILD_IDENTIFIER }}.build
