on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      source-branch:
        type: string
        required: false
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"
      bump-version:
        type: boolean
        required: false
        default: false
        description: "Bump artifact version"
      run-tests:
        type: boolean
        required: false
        default: false
        description: Spin up aerospike enterprise server and run tests

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ inputs.branch }}"
          echo "${{ github.base_ref }}"

  java-version:
    needs: debug-job
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.get-java-version.outputs.java-version }}
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Get java version
        id: get-java-version
        run: |
          echo java-version="$(grep '<java.version>' pom.xml | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1')" >> $GITHUB_OUTPUT

      - name: debug - print java-version
        run: |
          echo ${{ steps.get-java-version.outputs.java-version }}

  debug-java-version-job:
    runs-on: ubuntu-latest
    needs: java-version
    steps:
      - name: debug
        run: |
          echo "${{ needs.java-version.outputs.java-version }}"

  build:
    uses: ./.github/workflows/build.yaml
    needs: java-version
    strategy:
      matrix:
        crypto-type: [bouncycastle, gnu]
    with:
      java-version: ${{ needs.java-version.outputs.java-version }}
      branch: ${{ inputs.branch }}
      use-server-rc: ${{ inputs.use-server-rc }}
      run-tests: ${{ inputs.run-tests }}
      server-tag: ${{ inputs.server-tag }}
      upload-artifacts: ${{ inputs.upload-artifacts }}
      crypto-type: ${{ matrix.crypto-type }}
    secrets: inherit
