name: Promote to Prod

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_dispatch:
    inputs:
      build-number:
        type: number
        description: Build number used to build artifact to be promoted
      target-branch:
        type: choice
        description: Target branch to promote to
        options:
          - dev-stage

jobs:
  promote-from-stage-to-prod:
    name: Promote from stage to prod
    uses: ./.github/workflows/promote.yaml
    with:
      build-number: ${{ inputs.build-number }}
      target-repository: clients-maven-stage-local
      target-branch: ${{ inputs.target-branch }}
    secrets: inherit
