name: Promote to Stage

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  workflow_dispatch:
    inputs:
      build-number:
        type: number
        description: Build number used to build artifact to be promoted

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup jfrog shell
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_PLATFORM_URL }}
        with:
          oidc-provider-name: ${{ inputs.oidc-provider }}
          oidc-audience: ${{ inputs.oidc-audience }}

      - name: Get info
        id: get-build-info
        run: |
          echo build-info=$(jf rt curl /api/build/clients-java-push-to-dev/${{ inputs.build-number }}) >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo ${{ steps.get-build-info.outputs.build-info }}
