name: Publish release

on:
  workflow_dispatch:
    inputs:
      maven_central-release-id:
        type: string
        required: true
        description: Maven central staged release id

jobs:
  publish-release-to-maven-central:
    name: Publish release to Maven Centraal
    uses: ./.github/workflows/publish.yaml
    with:
      maven_central-release-id: ${{ inputs.maven_central-release-id }}
    secrets: inherit
