on:
  workflow_call:
    inputs:
      maven_central-release-id:
        type: string
        description: Build number used to build artifact to be promoted
    secrets:
      SONATYPE_MAVEN_USER:
        required: true
      SONATYPE_MAVEN_PASSWORD:
        required: true

jobs:
  publish-release:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: Validate staged build is valid and ready to be published
        run: |
          TOKEN=$(printf "${{ inputs.publish-user }}:${{ inputs.publish-password }}" | base64)

          echo "Request: curl --request POST --silent --header "Authorization: Bearer ${TOKEN}" --form bundle=@${{ steps.create-artifact.outputs.artifact-name }} ${{ inputs.sonatype_domain_name }}api/v1/publisher/deployment/${{ inputs.maven_central-release-id }}"
          echo stage-release-id=$(curl --request POST --silent --header "Authorization: Bearer ${TOKEN}" --form bundle=@${{ steps.create-artifact.outputs.artifact-name }} ${{ inputs.sonatype_domain_name }}api/v1/publisher/deployment/${{ inputs.maven_central-release-id }}) >> $GITHUB_OUTPUT
