name: PR open

permissions:
  # This is required for requesting the OIDC token
  id-token: write

on:
  pull_request:
    branches:
      - stage
      - stage-jdk8
      - dev/*
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      source-branch:
        type: string
        description: Base branch to use if manually starting. By default base_ref will empty if triggering manually hence base_ref is only available on PRs.

jobs:
  make-matrix:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    outputs:
      input-matrix: ${{ steps.set.outputs.input-matrix }}
      java-version: ${{ steps.get-java-version.outputs.java-version }}
    steps:
      - uses: actions/checkout@v4       # brings versions.json into the workspace
        with:
          ref: ${{ github.ref }}

      - id: set                         # create the matrix (compact JSON string)
        shell: bash
        env:
            DEFAULT_JSON: ${{ vars.DEFAULT_SERVER_VERSIONS }}
        run: |
          FILE=test_servers.json

          if [[ -s "$FILE" ]]; then
            echo "⚙️  Using $FILE from repository"
            JSON=$(cat "$FILE")
          else
            echo "⚠️  $FILE missing or empty – using DEFAULT_SERVER_VERSIONS"
            JSON="$DEFAULT_JSON"
          fi

          MATRIX=$(echo $JSON | jq -c '
              to_entries
              | map({server: .key, version: .value.version, "crypt-version": .value.crypto  })
          ')              # → [{"server":"rc","version":"8.1.0"}, …]
          echo "input-matrix=$MATRIX" >>"$GITHUB_OUTPUT"

      - name: Get java version
        id: get-java-version
        run: |
          echo java-version="$(grep '<java.version>' pom.xml | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1' | sed 's/^1\.8$/8/')"  >> $GITHUB_OUTPUT

      - name: debug - print input variables
        run: |
          echo ${{ steps.get-java-version.outputs.java-version }}
          echo ${{ steps.get-java-version.outputs.matrix }}

  build:
    uses: ./.github/workflows/build-pr.yaml
    needs: make-matrix
    strategy:
      matrix: ${{ fromJson(needs.make-matrix.outputs.input-matrix) }}
    name: build-${{ matrix.server }}-${{ matrix.version }}-${{ needs.make-matrix.outputs.java-version }}
    with:
      java-version: ${{ needs.make-matrix.outputs.java-version }}
      run-tests: true 
      server-tag: ${{ matrix.version }}
      crypto-type: ${{ matrix.crypto-type }}
    secrets: inherit