on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "${{ inputs.branch }}"
          echo "${{ github.base_ref }}"

  java-version:
    needs: debug-job
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.get-java-version.outputs.java-version }}
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Get java version
        id: get-java-version
        run: |
          echo java-version="$(grep '<java.version>' pom.xml | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1')" >> $GITHUB_OUTPUT

      - name: Debug - java-version
        run: |
          echo ${{ steps.get-java-version.outputs.java-version }}

  build:
    uses: ./.github/workflows/release.yaml
    needs: java-version
    strategy:
      matrix:
        crypto-type: [bouncycastle, gnu]
    with:
      java-version: ${{ needs.java-version.outputs.java-version }}
      branch: ${{ inputs.branch }}
      crypto-type: ${{ matrix.crypto-type }}
    secrets: inherit

  aggregate-published-artifacts:
    uses: ./.github/workflows/aggregate-build.yaml
    needs: [java-version, build]
    secrets: inherit
    with:
      java-version: ${{ needs.java-version.outputs.java-version }}
