on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      version:
        type: string
        required: false
      build-number:
        type: string
        required: true
      is-snapshot:
        type: boolean
        required: false
        default: true

jobs:
  debug-job:
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    steps:
      - name: debug
        run: |
          echo "${{ inputs.ref }}"
          echo "${{ github.base_ref }}"

  java-version:
    needs: debug-job
    runs-on: ${{ vars.BUILD_CONTAINER_DISTRO_VERSION }}
    outputs:
      java-version: ${{ steps.get-java-version.outputs.java-version }}
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Get java version
        id: get-java-version
        run: |
          echo java-version="$(grep '<java.version>' pom.xml | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1')" >> $GITHUB_OUTPUT

      - name: Debug - java-version
        run: |
          echo ${{ steps.get-java-version.outputs.java-version }}

  build:
    uses: ./.github/workflows/release.yaml
    needs: java-version
    strategy:
      matrix:
        crypto-type: [bouncycastle, gnu]
    with:
      ref: ${{ inputs.ref }}
      java-version: ${{ needs.java-version.outputs.java-version }}
      crypto-type: ${{ matrix.crypto-type }}
      version: ${{ inputs.version }}
      is-snapshot: ${{ inputs.is-snapshot }}
    secrets: inherit

  aggregate-published-artifacts:
    uses: ./.github/workflows/aggregate-build.yaml
    needs: [java-version, build]
    secrets: inherit
    with:
      java-version: ${{ needs.java-version.outputs.java-version }}
