name: Test and build on-demand

on:
  workflow_dispatch:
    inputs:
      source-branch:
        type: string
        required: true
        description: Branch to run test against

jobs:
  build-and-test:
    uses: ./.github/workflows/test-branch.yaml
    needs: pre-requisites
    strategy:
      matrix:
        crypto-type: [bouncycastle, gnu]
        use-server-rc: [true, false]
    with:
      source-branch: ${{ inputs.source-branch }}
      crypto-type: ${{ matrix.crypto-type }}
      use-server-rc: ${{ matrix.use-server-rc }}
