{
 "title": "Aerospike Benchmark MRT",
 "description": "Dashboard for the Aerospike MRT Benchmark application",
 "tags": [
  "aerospike",
  "mrt",
  "monitor",
  "benchmark"
 ],
 "time": { "from": "2024-11-18T21:38:58.167Z", "to": "2024-11-18T21:41:15.550Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_heartbeat,clustername)"
    }
   },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_heartbeat{clustername=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "description": "Cluster Name",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Node",
   "type": "stat",
   "description": "The DB Node Address",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "stat",
   "description": "Connection State",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "description": "Namespace",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Set name",
   "type": "stat",
   "description": "Set used by the benchmark application",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "client" },
  {
   "title": "General",
   "type": "stat",
   "description": "General Configuration Information used to run the Benchmark application",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "description": "Aerospike Policies used in the Benchmark application.",
   "gridPos": { "h": 6, "w": 10, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "stat",
   "description": "Other Configuration Information used to run the Benchmark application",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Count",
   "type": "stat",
   "description": "The total number of actions",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The total number of errors",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "description": "The total number of Exceptions",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "The total number of Timeouts",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "description": "The total number of MRT transactions",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trxn Errors",
   "type": "stat",
   "description": "The total number of MRT transaction Errors",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trxn Timeouts",
   "type": "stat",
   "description": "The total number of MRT transaction Timeouts",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "stat",
   "description": "The total number of Writes",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "stat",
   "description": "The total number of Write Errors",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Timeouts",
   "type": "stat",
   "description": "The total number of Write Timeouts",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Counts",
   "type": "stat",
   "description": "The total number of Reads",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "stat",
   "description": "The total number of Read Errors",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Timeouts",
   "type": "stat",
   "description": "The total number of Read Timeouts",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_heartbeat{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Write TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=\"write\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_latency_milliseconds_bucket{instance=~\"$client\", type=\"write\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Read TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=\"read\"}[$__rate_interval])",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(le) (aerospike_benchmarks_mrt_latency_milliseconds_bucket{instance=~\"$client\", type=\"read\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}