{
 "title": "Aerospike Benchmark MRT (us)",
 "description": "Dashboard for the Aerospike MRT Benchmark application where latency is measured in microseconds",
 "tags": [
  "aerospike",
  "mrt",
  "monitor",
  "benchmark",
  "microseconds"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "label": "Data Source", "query": "prometheus" },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_stateinfo,instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "setname",
    "label": "Set name",
    "query": {
     "query": "label_values(aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", namespace=~\"$namespace\", cluster=~\"$cluster\"},setname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "description": "Cluster Name",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Node",
   "type": "stat",
   "description": "The DB Node Address",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection State",
   "type": "stat",
   "description": "Connection State",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "description": "Namespace",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", namespace=~\"$namespace\", setname=~\"$setname\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Set name",
   "type": "stat",
   "description": "Set used by the benchmark application",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start and Completion Time",
   "type": "stat",
   "description": "The benchmark's starting and completion time",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "General",
   "type": "stat",
   "description": "General Configuration Information used to run the Benchmark application",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "description": "Aerospike Policies used in the Benchmark application.",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Other",
   "type": "stat",
   "description": "Other Configuration Information used to run the Benchmark application",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "stat",
   "description": "Set the number of keys the client is dealing with. If using an 'insert' workload, the client will write this number of keys. Otherwise, the client will read and update randomly based on this number.",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "description": "The action limit",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Load",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Percent",
   "type": "stat",
   "description": "Percent of reads",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Percent",
   "type": "stat",
   "description": "Percent of writes",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Async Enable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput Throttle",
   "type": "stat",
   "description": "The number of actions when the throttle is applied",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Line Argument",
   "type": "stat",
   "description": "The command line argument provided to the benchmark appllication",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MRT Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "MRT Transaction Timeout",
     "type": "stat",
     "description": "The timeout of a MRT transaction. If reached the server will rollback the transaction.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Size",
     "type": "stat",
     "description": "The number of actions per MRT (Unit of Work)",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT/Task",
     "type": "stat",
     "description": "The number of MRTs (Unit of Work) per task (thread). ",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT InDoubt Retries",
     "type": "stat",
     "description": "The number of retries when a Commit is \"InDoubt\" state",
     "gridPos": { "h": 3, "w": 3, "x": 7, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT InDoubt Sleep",
     "type": "stat",
     "description": "The sleep time between InDoubt Commit Retries",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Block Retries",
     "type": "stat",
     "description": "The number of retries when an action is blocked",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Block Sleep",
     "type": "stat",
     "description": "The sleep time between Block Retries",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_stateinfo{instance=~\"$client\", type=\"static\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Current/Last Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Completed RW Count",
   "type": "stat",
   "description": "The total completed number of read and write operations",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"write|read|readnotfound\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Total Completed Write Count",
   "type": "stat",
   "description": "The total completed number of write actions across all types",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=\"write\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Total Completed Read Count",
   "type": "stat",
   "description": "The total completed number of read actions across all types",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"read|readnotfound\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "description": "The total number oferrors",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_exception_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Total Unit of Work (MRTs) Transaction",
   "type": "stat",
   "description": "The total number of Unit of Work (MRTs) that made it to either commit or abort point. MRT size determines the number of actions within a Unit of Work.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtuow\"}[$__interval]))",
     "legendFormat": "No Latency"
    }
   ]
  },
  {
   "title": "Total Coimpleted Commits",
   "type": "stat",
   "description": "The total completed number of Commits",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtcommit\"}[$__interval]))",
     "legendFormat": "No Latency"
    }
   ]
  },
  {
   "title": "Total Completed Aborts",
   "type": "stat",
   "description": "The total completed number of Aborts. An abort can occur if an action (e.g., get or put) fails or the commit fails. ",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtabort\"}[$__interval]))",
     "legendFormat": "No Latency"
    }
   ]
  },
  {
   "title": "Total MRT Related Errors",
   "type": "stat",
   "description": "The total number of MRT Related Errors",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(aerospike_benchmarks_mrt_related_errors_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__interval]))",
     "legendFormat": "Not Measured"
    }
   ]
  },
  {
   "title": "Time Range Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Range Total Completed RW Count",
     "type": "stat",
     "description": "The total completed number of read and write operations",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"write|read|readnotfound\"}[$__range]))",
       "legendFormat": "Not Measured"
      }
     ]
    },
    {
     "title": "Range Total Completed Write Count",
     "type": "stat",
     "description": "The total completed number of write actions across all types",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=\"write\"}[$__range]))",
       "legendFormat": "Not Measured"
      }
     ]
    },
    {
     "title": "Range Total Completed Read Count",
     "type": "stat",
     "description": "The total completed number of read actions across all types",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"read|readnotfound\"}[$__range]))",
       "legendFormat": "Not Measured"
      }
     ]
    },
    {
     "title": "Range Total Errors",
     "type": "stat",
     "description": "The total number oferrors",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_exception_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__range]))",
       "legendFormat": "Not Measured"
      }
     ]
    },
    {
     "title": "Range Total Unit of Work (MRTs) Transaction",
     "type": "stat",
     "description": "The total number of Unit of Work (MRTs) that made it to either commit or abort point.",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtuow\"}[$__range]))",
       "legendFormat": "No Latency"
      }
     ]
    },
    {
     "title": "Range Total Completed Commits",
     "type": "stat",
     "description": "The total completed number of Commits",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtcommit\"}[$__range]))",
       "legendFormat": "No Latency"
      }
     ]
    },
    {
     "title": "Range Total Completed Aborts",
     "type": "stat",
     "description": "The total completed number of Aborts",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtabort\"}[$__range]))",
       "legendFormat": "No Latency"
      }
     ]
    },
    {
     "title": "Range Total Errors",
     "type": "stat",
     "description": "The total number oferrors",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(aerospike_benchmarks_mrt_related_errors_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__range]))",
       "legendFormat": "Not Measured"
      }
     ]
    }
   ]
  },
  {
   "title": "Quantile Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Quantile P50",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "min by(type) (histogram_quantile(0.5, aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type!~\"mrtuow|mrtuowtotal\", namespace=~\"$namespace\", setname=~\"$setname\"}))",
       "legendFormat": "p50 {{type}}"
      }
     ]
    },
    {
     "title": "Latency Quantile P75",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "min by(type) (histogram_quantile(0.75, aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", type!~\"mrtuow|mrtuowtotal\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}))",
       "legendFormat": "p75 {{type}}"
      }
     ]
    },
    {
     "title": "Latency Quantile P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "min by(type) (histogram_quantile(0.9, aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", type!~\"mrtuow|mrtuowtotal\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}))",
       "legendFormat": "p90 {{type}}"
      }
     ]
    },
    {
     "title": "Latency Quantile P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "min by(type) (histogram_quantile(0.95, aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", type!~\"mrtuow|mrtuowtotal\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}))",
       "legendFormat": "p95 {{type}}"
      }
     ]
    },
    {
     "title": "Latency Quantile P99",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "min by(type) (histogram_quantile(0.99, aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", type!~\"mrtuow|mrtuowtotal\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}))",
       "legendFormat": "p99 {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quantile TPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS Quantile P50",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(type) (quantile_over_time(0.5, rate(aerospike_benchmarks_mrt_latency_microsecond_count{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by(type) (quantile_over_time(0.5, rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}} NL"
      }
     ]
    },
    {
     "title": "TPS Quantile P75",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(type) (quantile_over_time(0.75, rate(aerospike_benchmarks_mrt_latency_microsecond_count{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by(type) (quantile_over_time(0.75, rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}} NL"
      }
     ]
    },
    {
     "title": "TPS Quantile P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(type) (quantile_over_time(0.90, rate(aerospike_benchmarks_mrt_latency_microsecond_count{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by(type) (quantile_over_time(0.90, rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}} NL"
      }
     ]
    },
    {
     "title": "TPS Quantile P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(type) (quantile_over_time(0.95, rate(aerospike_benchmarks_mrt_latency_microsecond_count{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by(type) (quantile_over_time(0.95, rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}} NL"
      }
     ]
    },
    {
     "title": "TPS Quantile P99",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "avg by(type) (quantile_over_time(0.99, rate(aerospike_benchmarks_mrt_latency_microsecond_count{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "avg by(type) (quantile_over_time(0.99, rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", type=~\"read|readnotfound|write\",cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])[$__range:5s]))",
       "legendFormat": "{{type}} NL"
      }
     ]
    }
   ]
  },
  { "title": "Write (Put)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Write TPS",
   "type": "timeseries",
   "description": "A \"put\" action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\",cluster=~\"$cluster\",namespace=~\"$namespace\",setname=~\"$setname\", type=\"write\"}[$__rate_interval])",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Write Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(le) (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\",cluster=~\"$cluster\",namespace=~\"$namespace\",setname=~\"$setname\", type=\"write\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "timeseries",
   "description": "The number of writes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=\"write\"}[$__rate_interval])",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (histogram_quantile(0.95, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=\"write\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.99, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=\"write\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.999, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=\"write\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p99.9"
    }
   ]
  },
  { "title": "Read (Get)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Read TPS",
   "type": "timeseries",
   "description": "A \"Get\" action",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"read|readnotfound\"}[$__rate_interval])",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Read Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum by(le) (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\",cluster=~\"$cluster\",namespace=~\"$namespace\",setname=~\"$setname\", type=~\"read|readnotfound\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Read Count",
   "type": "timeseries",
   "description": "The number of reads",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"read|readnotfound\"}[$__rate_interval])",
     "legendFormat": "{{type}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "stat",
   "description": "Average across all nodes counted into buckets from 0 to 2^16",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (namespace) (histogram_quantile(0.95, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"read|readnotfound\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.99, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"read|readnotfound\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p99"
    },
    {
     "expr": "avg by (namespace) (histogram_quantile(0.999, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"read|readnotfound\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "MRTs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "MRT Latencies Commit",
     "type": "heatmap",
     "description": "The latency of a MRT commit",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum by(le) (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtcommit\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Latencies Abort",
     "type": "heatmap",
     "description": "The latency of a MRT abort",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
     "targets": [
      {
       "expr": "sum by(le) (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtabort\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Latencies Unit of Work (MRT) in Milliseconds",
     "type": "heatmap",
     "description": "The latency of a MRT Unit of Work which represents the DB actions (gets/outs) defined within the MRT. The number of these actions is defined by the MRTSize parameter.  This does NOT include the time taken to compete the commit or abort.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum by(le) (aerospike_benchmarks_mrt_lng_latency_milliseconds_bucket{instance=~\"$client\",cluster=~\"$cluster\",namespace=~\"$namespace\",setname=~\"$setname\", type=\"mrtuow\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Latencies Complete Unit of Work (MRT) in Milliseconds",
     "type": "heatmap",
     "description": "The latency of a MRT Unit of Work  plus the associated commit/abort.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "expr": "sum by(le) (aerospike_benchmarks_mrt_lng_latency_milliseconds_bucket{instance=~\"$client\",cluster=~\"$cluster\",namespace=~\"$namespace\",setname=~\"$setname\", type=~\"mrtuowtotal\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MRT Counts",
     "type": "timeseries",
     "description": "The number of MRT Action Counts (MRTs, Commits, and Aborts)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "increase(aerospike_benchmarks_mrt_transaction_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\", type=~\"mrtuow|mrtcommit|mrtabort|mrtuowtotal\"}[$__rate_interval])",
       "legendFormat": "{{type}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Percentiles (Commit/Abort)",
     "type": "stat",
     "description": "Average across all nodes counted into buckets from 0 to 2^16",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (namespace) (histogram_quantile(0.95, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"mrtcommit|mrtabort\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
       "legendFormat": "p95"
      },
      {
       "expr": "avg by (namespace) (histogram_quantile(0.99, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"mrtcommit|mrtabort\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
       "legendFormat": "p99"
      },
      {
       "expr": "avg by (namespace) (histogram_quantile(0.999, (aerospike_benchmarks_mrt_latency_microsecond_bucket{instance=~\"$client\", cluster=~\"$cluster\", type=~\"mrtcommit|mrtabort\", namespace=~\"$namespace\", setname=~\"$setname\"})))",
       "legendFormat": "p99.9"
      }
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "All Error",
   "type": "timeseries",
   "description": "All Errors",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(aerospike_benchmarks_mrt_exception_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])",
     "legendFormat": "{{type}} - {{instance}} - {{exception_type}}: {{exception}}"
    }
   ]
  },
  {
   "title": "Total Error Counts",
   "type": "table",
   "description": "The total number of errors",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aerospike_benchmarks_mrt_exception_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}",
     "legendFormat": "{{type}} - {{exception_type}}: {{exception}}"
    }
   ]
  },
  {
   "title": "MRT Related Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "MRT Related Errors",
     "type": "timeseries",
     "description": "Errors",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "increase(aerospike_benchmarks_mrt_related_errors_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}[$__rate_interval])",
       "legendFormat": "{{error_type}} - {{instance}} - {{type}}"
      }
     ]
    },
    {
     "title": "Total Error Counts",
     "type": "table",
     "description": "The total number of errors",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "aerospike_benchmarks_mrt_related_errors_total{instance=~\"$client\", cluster=~\"$cluster\", namespace=~\"$namespace\", setname=~\"$setname\"}",
       "legendFormat": "{{type}} - {{exception_type}}: {{exception}}"
      }
     ]
    }
   ]
  }
 ]
}